apps/home/urls.py
from django.conf.urls import url

urlpatterns = [

]

scrapper/urls.py
"""Urls for the scrapper project."""
from django.conf.urls import include, url
from django.contrib import admin
# from apps import checkout
from apps.home import views
from apps.checkout.views import PaymentView
from apps.checkout.views import DeliveryDetailsView
from apps.checkout.views import SummaryView
from django.conf import settings
# import apps

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^signup/$', 'apps.usermanager.views.signup', name='signup'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {"next_page": "/"}, name='logout'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^login/$', 'apps.usermanager.views.app_login', name='app_login'),
    url(r'^activate/$', 'apps.usermanager.views.activate', name='activate'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/edit$', views.EditProfileView.as_view(),
        name='edit_profile'),
    url(r'^dashboard/scrap$', views.ScrapView.as_view(), name='scrap'),
    url(r'dashboard/filter/$', views.DashboardFilterView.as_view(),
        name='dashboard_filter'),
    url(r'^product/(?P<name>[-\w\d]+)/$', views.ProductDisplayView.as_view(), name="product_display"),
    url(r'^checkout/payment/$', PaymentView.as_view(), name='payment'),
    url(r'^checkout/address/$', DeliveryDetailsView.as_view(), name='delivery_address'),
    url(r'^checkout/summary/$', SummaryView.as_view(), name='summary'),
    url(r'^docs/', include('sphinxdoc.urls')),
    # url(r'^docs/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.DOCS_ROOT}),
    # url(r'^docs/', 'django.views.static.serve', {'document_root': settings.DOCS_ROOT, 'path': 'index.html'}),

    # url(r'^docs/', 'django.views.static.serve', {'document_root': settings.DOCS_ROOT, 'path': 'index.html'}),
    # url(r'^docs/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.DOCS_ROOT}),
    # url(r'^docs/', include('docs.urls')),
]

apps/home/models.py
"""Model used for scrapping items and storing in the database."""
from django.db import models
from django.template.defaultfilters import slugify


class Product(models.Model):
    """Model for storing the details of the product."""

    # details of the product, the date on which it is scrapped,
    # the website where the product is being sold, and the product's slug name
    name = models.CharField(max_length=255, null=True, blank=True)
    product_type = models.CharField(max_length=30, null=True, blank=True)
    price = models.FloatField(default=0.0, null=True, blank=True)
    landing_url = models.URLField(null=True, blank=True)
    image = models.URLField(null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    scraped_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    site_reference = models.CharField(max_length=50, null=True, blank=True)
    slug_name = models.SlugField(max_length=255, null=True, blank=True)

    def __str__(self):
        """Value to return if object is called."""
        return self.name

    def save(self, *args, **kwargs):
        """Slugifying the name field."""
        self.slug_name = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

apps/usermanager/models.py
"""Models for user details and user acitvation."""
from django.db import models
from django.contrib.auth.models import User
from apps import constants
from django.utils import timezone


def generate_filename(self, filename):
    """Used for handling upload file."""
    url = "static/uploads/%s/%s" % (self.pk, filename)
    return url


class UserDetail(models.Model):
    """Model for storing user details."""

    # one-to-one relation with the auth_user table
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    date_of_birth = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    marital = models.CharField(
        max_length=1, choices=constants.MARITAL_CHOICES, null=True, blank=True)
    gender = models.CharField(
        max_length=1, choices=constants.GENDER_CHOICES, null=True, blank=True)

    # address fields
    address = models.CharField(max_length=254, null=True, blank=True)
    street = models.CharField(max_length=30, null=True, blank=True)
    city = models.CharField(max_length=30, null=True, blank=True)
    state = models.CharField(max_length=30, null=True, blank=True)
    zip_code = models.CharField(max_length=6, null=True, blank=True)

    # contact field
    phone = models.CharField(max_length=20, null=True, blank=True)

    # extra note field (textarea in form)
    extra_note = models.CharField(max_length=254, null=True, blank=True)

    # prefered communication (checkbox fields in form)
    mail = models.BooleanField(default=False)
    message = models.BooleanField(default=False)
    phonecall = models.BooleanField(default=False)
    other = models.BooleanField(default=False)

    # profile pic field
    image = models.ImageField(
        upload_to='static/uploads/', null=True, blank=True)

    def __str__(self):
        """Value to return if object is called."""
        return self.city


class UserActivation(models.Model):
    """Model for storing the acitvation key."""

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    activation_key = models.CharField(max_length=40, blank=True)
    key_expires = models.DateTimeField(default=timezone.now)

    def __str__(self):
        """Value to return if object is called."""
        return self.user.username

apps/home/forms.py
"""Forms used in dashboard.

Scrap form, dashboard search form, filter form used in the dashboard page.
"""
from django import forms
from apps import constants


class ScrapSearchForm(forms.Form):
    """Search form to scrap items."""

    # search textbox
    search = forms.CharField(
        max_length=255, required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control', 'required': True
        })
    )
    # radio button to select website
    site_choice = forms.ChoiceField(
        choices=constants.SITE_CHOICES, required=True,
        widget=forms.RadioSelect(attrs={'required': True})
    )


class DashboardSearchForm(forms.Form):
    """Search form to search products in the dashboard from the database."""

    # search textbox
    search = forms.CharField(
        max_length=255, required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control sharp-corner-right', 'required': True,
            'placeholder': 'What would you like to search?'
        })
    )


class DashboardFilterForm(forms.Form):
    """Search products from database.

    It provide all the fields needed for search form.
    """

    # Radio fields.
    price_sort = forms.ChoiceField(
        required=False, choices=constants.PRICE_CHOICES,
        widget=forms.RadioSelect(attrs={
            'class': 'filter-click',
            'required': False
        })
    )

    # Checkbox fields.
    amazon = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'filter-click'})
    )
    flipkart = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'filter-click'})
    )

apps/home/views.py
"""View for the home page.

Home page view, dashboard view, filter in dashboard, displaying the
product page profile page and edit page.
"""
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from apps.usermanager import forms
from django.contrib.auth.models import User
from apps.usermanager.models import UserDetail
from django.conf import settings
import os
from apps.home.scrap import Scrap
from apps.home.forms import ScrapSearchForm
from apps.home.forms import DashboardSearchForm
from apps.home.forms import DashboardFilterForm
from apps.home.models import Product
from django.db.models import Q
from django.shortcuts import render_to_response
from django.template import RequestContext
import logging
from apps import constants
import json
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.core.cache import cache
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse


class HomeView(TemplateView):
    """Class for the home page view."""

    template_name = 'home/home.html'

    def get(self, request, *args, **kwargs):
        """Get method for HomeView class."""
        ctx = {'title': 'Home', 'home': 'active'}
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        """Post method for HomeView class."""
        pass


class DashboardView(TemplateView):
    """View for the dashboard.

    Allows user to search for the product,
     and display the result in the front end.
    The results are fetched from the database.
    """

    template_name = 'home/dashboard.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        """Get method for DashboardView class."""
        products = []
        result_error = ""
        if request.is_ajax():
            # search form
            form = DashboardSearchForm(request.GET)
            # filter form
            form2 = DashboardFilterForm(request.GET)

            if form.is_valid():
                data = form.cleaned_data
                search_item = data['search']

                # getting the products whose name or price or site reference or
                # product type or description matches with the search item
                products = Product.objects.filter(
                    Q(name__icontains=search_item) |
                    Q(price__icontains=search_item) |
                    Q(site_reference__icontains=search_item) |
                    Q(product_type__icontains=search_item) |
                    Q(description__icontains=search_item)
                )

                # when resuts are found initial 'resutl' variable
                if products:
                    result = products
                # otherwise initialize error message
                else:
                    result = None
                    result_error = True

                # storing the searched result in the cache,
                # in order to use it in the DashboardFilterView
                cache.set('product_result', result, None)

                # create a dictionary to hold the result and the error feedback
                ctx = {
                    'result': result, 'dashboard_result_error': result_error}
                html = render_to_string(
                    'home/result.html', ctx,
                    context_instance=RequestContext(request))
                # encoding it to json
                json_data = json.dumps({'result': html})
                # sending the json response
                return HttpResponse(json_data, content_type='application/json')
        else:
            form = DashboardSearchForm()
            form2 = DashboardFilterForm()

        # create a dictionary for the context
        ctx = {
            'title': 'Dashboard', 'dashboard': 'active', 'form': form,
            'result': products, 'result_error': result_error, 'form2': form2
        }
        return render(request, self.template_name, ctx)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        """Post method for DashboardView class."""
        pass


class DashboardFilterView(TemplateView):
    """View for filtering the results in the dashboard.

    The results can be filtered according to price, site choice etc.
    """

    template_name = 'home/dashboard.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        """Filtering the results based on price, site choice etc."""
        result_error = ""
        # storing the search results in 'results' and applying filters to it'
        result = cache.get('product_result')
        if request.is_ajax():
            form2 = DashboardFilterForm(request.GET)
            if form2.is_valid():
                filter_data = form2.cleaned_data
                if result:

                    # sorting price of the result in ascending order
                    if filter_data['price_sort'] == 'LH':
                        result = result.order_by('price')
                    # sorting price of the result in descending order
                    elif filter_data['price_sort'] == 'HL':
                        result = result.order_by('-price')

                    # filtering the results for both amazon and flipkart,
                    # i.e when user check both flipkart and amzon
                    if filter_data['amazon'] and filter_data['flipkart']:
                        pass
                    # filtering the results which are only from amazon
                    elif filter_data['amazon']:
                        result = result.filter(
                            Q(site_reference__icontains='amazon'))
                    # filtering the results which are only from flipkart
                    elif filter_data['flipkart']:
                        result = result.filter(
                            Q(site_reference__icontains='flipkart'))

                # when no results are found, display the error message,
                # set the result error flag to true
                else:

                    # make result to none.
                    result = None
                    result_error = True

            else:
                logger = logging.getLogger(constants.LOGGER)
                logger.error("Wrong data")

            # create the context
            ctx = {'result': result, 'dashboard_result_error': result_error}
            html = render_to_string(
                'home/result.html', ctx,
                context_instance=RequestContext(request))
            # encoding it to json
            json_data = {'result': html}
            # sending the json response
            return HttpResponse(
                json.dumps(json_data), content_type='application/json')

        # Contexts to send in html.
        ctx = {
            'title': 'Dashboard page', 'dashboard': 'active',
            'form2': form2}
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        """Post method for DashboardFilterView."""
        pass


class ProductDisplayView(TemplateView):
    """View to display the product detail."""

    template_name = 'home/product_display.html'

    @method_decorator(login_required)
    def get(self, request, name, *args, **kwargs):
        """Get method for ProductDisplayView class."""
        # fetching the product from the given slug name of the product
        product = Product.objects.filter(slug_name=name)
        try:
            # fetching the product id of the selected product
            pk = product[0].pk
        except:
            return HttpResponseRedirect(reverse('dashboard'))

        # storing the product id in the cache
        cache.set('product_id', pk, None)

        # storing the price of the product in the cache
        cache.set('price', product[0].price, None)

        # creating the context and rendering the html page where the particular
        # product will be displayed
        ctx = {
            'product': product[0], 'title': 'Dashboard', 'dashboard': 'active'
        }
        return render(request, self.template_name, ctx)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        """Post method for ProductDisplayView class."""
        pass


class ProfileView(TemplateView):
    """View for Profile page.

    The profile of the logged in user is displayed.
    """

    template_name = 'home/profile.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        """Get method for ProfileView class."""
        # create the context and render the html page
        ctx = {'title': 'Profile'}
        return render(request, self.template_name, ctx)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        """Post method for ProfileView class."""
        pass


class EditProfileView(TemplateView):
    """View for Edit Profile page.

    The user can edit his profile from this view.
    """

    template_name = 'home/edit_profile.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        """Get method for ProfileView class."""
        form = forms.EditProfileForm(request)
        return render(request, self.template_name, {
            'form': form, 'title': 'Edit Profile'})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        """Post method for EditProfileView class."""
        form = forms.EditProfileForm(request, request.POST, request.FILES)

        # if the form is valid and its attribute enctype="multipart/form-data"
        if form.is_valid() and form.is_multipart():
            try:
                # initialize 'data' with the cleaned data

templates/home/dashboard.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block home-marquee %}
<!-- search form in dashboard-->
<div class="row dashboard">
 	<div class = "col-xs-12">
		<!-- search box -->
		<div class="row">
			<div class="col-xs-12">
				<form action="{% url 'dashboard' %}" method='get' id="dashboard_search_form">
					<div class="form-group col-xs-6 col-xs-offset-2 has-feedback stick-text">
						{{ form.non_field_errors }}
						<!-- if the field contains errors display error message -->
						{% if form.search.errors %}
							<div class="has-error has-feedback">
								{{ form.search }}
								<span class="help-inline text-danger">
				                    {% for error in  form.search_item.errors %}{{ error }}{% endfor %}
				                </span>
				                 <i class="glyphicon glyphicon-remove form-control-feedback"></i>
							</div>
						{% else %}
						<!-- search textfield -->
							<div class="controls has-feedback inner-addon left-addon">
								<i class="glyphicon glyphicon-search form-control-feedback"></i>
		 						{{form.search}}
		 						
							</div>
						{% endif %}					
					</div>
					<!-- submit button -->
					<div class="form-group col-xs-2 stick-submit">
						<button type="submit" id="dashboard_search_submit" name="dashboard_search_submit" class="sharp-corner-left btn btn-primary " >Search</button>
					</div>
				</form>
			</div>
		</div>		
	</div>
	<div class="row">
		<!-- filter panel -->
		<div class="col-sm-3 filter-panel">
			<!-- filter panel1 price sorting -->
			<form action="{% url 'dashboard_filter' %}" id="dashboard_filter_form" method="get" >
				<div class="page-header"></div>
				<div class="panel-group">
				    <div class="panel">
				        <div class="panel-heading">
				          <h4 class="panel-title">
				              <a data-toggle="collapse" href="#collapse1">Price Sort</a>
				          </h4>
				        </div>
				        <div id="collapse1" class="panel-collapse collapse in">
				            <div class="panel-body">
				            	{% for field in  form2.price_sort %}
				            		<div>
				            			{{ field }}
				            		</div>
				            	{% endfor %}					   			           
				            </div>
				        </div>
				    </div>
				</div>
				 <!-- filter panel2 site choice -->
				<div class="page-header"></div>
				<div class="panel-group">
				    <div class="panel">
				        <div class="panel-heading">
				          <h4 class="panel-title">
				              <a data-toggle="collapse" href="#collapse2">Site Choice</a>
				          </h4>
				        </div>
				        <div id="collapse2" class="panel-collapse collapse in">
				            <div class="panel-body">

				            	<div class="checkbox">								 
									<label>
										{{form2.amazon}} Amazon
									</label>
								</div>
								<div class="checkbox">								 
									<label>
										{{form2.flipkart}} Flipkart
									</label>
								</div>
				            </div>
				        </div>
				    </div>
				</div>
			</form>
		</div>

		<!-- area for displaying the results -->
		<div id="result_area" class="col-sm-9">
		</div>
		
		<!-- loading image -->
		<div class="col-sm-12">
			<div class="load_div col-sm-12" id="load_div"><div class="text-center"><img class="loading_img" width="140px" height="140px" src="{% static 'images/loader3.gif' %}"></div></div>
		</div>
	</div>
</div>
{% endblock%}

templates/home/product_display.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block home-marquee %}
	<div class="col-sm-8 col-sm-offset-2" style="min-height : 700px; padding-top: 17%; padding-bottom: 5%;"> 
		{% if product %} 
		<div class="col-sm-12">
			<!-- displaying the image -->
			<div class="col-md-3 text-center">
				<a href="{{product.landing_url}}" target="_blank" >
					<img class="text-center" src="{{product.image}}"/>
				</a>
			</div>
			<div class="col-sm-9">
				<!-- displaying the name -->
				<div class="col-sm-12">
					<a href="{{product.landing_url}}" target="_blank" ><h4>{{product.name}}</h4></a>
				</div>
				<!-- displaying the price -->
				<div class="col-sm-12">
					<h4>Rs: <a href="{{product.landing_url}}" target="_blank" ><span class="text-danger">{{product.price}}</span></h4></a>
				</div>
				<!-- displaying the category -->
				<div class="col-sm-12">
					<h5>Category : {{product.product_type}}</h5>
				</div>
				<!-- displaying the site reference -->
				<div class="col-sm-12">
					<h5>In : {{product.site_reference}}</h5>
				</div>
			</div>
			<!-- buy button of the product -->
			<div class="col-sm-12 col-sm-offset-3">
				<!-- buy form scrappler.com -->
				<div class="col-sm-12">
					<a href="{% url 'delivery_address' %}" class="btn product-display-buy-button btn-lg btn-warning">Buy</a>
				</div>			
			</div>
		</div>
		{%else%}
			no product
		{%endif%}
	</div>
{% endblock %}

templates/home/profile.html
{% load static %}
<html>
	<head>
		<!-- content inside the head tag of an html page -->
		<meta charset="UTF-8">
		<!--tell the IE to use the latest rendering engine-->
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
		<!--set the page width to size of the device and zoom level to 1-->
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<title>{{title}}</title>
		<!-- stylesheet -->
		<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">	
		<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/scrolling-nav.css' %}">

	</head>
	<body>
		<!-- naviagation bar -->
		{% include 'navbar_dashboard.html' %}
		<!-- profile page content -->
		<div class="container-fluid profile-background">
		    <div class="row profile">
				<div class="col-md-3">
					<div class="profile-sidebar">
						<!-- sidebar userpic -->
						<div class="profile-userpic">
							<img src="{% get_static_prefix %}{{user.userdetail.image}}" class="img-responsive" alt="Image not found ">
						</div>

						<!-- sidebar user title -->
						<div class="profile-usertitle">
							<div class="profile-usertitle-name">
								{{user.first_name}} {{user.last_name}}
							</div>
							<div class="profile-usertitle-job email">
								{{user.email}}
							</div>
						</div>

						<!-- sidebar user menu, displaying link for profile, edit profile and logout -->
						<div class="profile-usermenu">
							<ul class="nav">
								<!-- displaying the profile -->
								<li class="active">
									<a href="{% url 'profile' %}">
									<i class="glyphicon glyphicon-home"></i>
									Overview </a>
								</li>
								<!-- link for editing the profile -->
								<li>
									<a href="{% url 'edit_profile' %}">
									<i class="glyphicon glyphicon-user"></i>
									Edit Profile </a>
								</li>
								<!-- link for logging out -->
								<li>
									<a href="{% url 'logout' %}">
									<i class="glyphicon glyphicon-log-out"></i>
									Log out </a>
								</li>
							</ul>
						</div>
					</div>
				</div> <!--col-md-3-->

				<!-- profile content, displaying all the fields for viewing the profile -->
				<div class="col-md-9">
		            <div class="profile-content">
		            	<!-- heading -->
						<div class="row">
							<div class="col-md-12">
								<div class="page-header">
									<h1>
										Profile
									</h1>
								</div>
							</div>
						</div>
						<!-- personal information -->
						<div class="row">
							<div class="col-md-12">
								<table class="table borderless">
									<!-- name -->
									<tr>
										<th class="col-md-3"><p>Personal Information</p></th>
										<td class="col-md-3"><p>Name:</p></td>
										<td class="col-md-6"><P>{{user.first_name}} {{user.last_name}}</P></td>
									</tr>
									
									<!-- gender -->
									<tr>
										<td class="col-md-3"></td>
										<td class="col-md-3"><p>Gender:</p></td>
										<td class="col-md-6"><P>{{user.userdetail.get_gender_display}}</P></td>
									</tr>

									<!-- date of birth -->
									<tr>
										<td class="col-md-3"></td>
										<td class="col-md-3"><p>Date of birth:</p></td>
										<td class="col-md-6"><P>{{user.userdetail.date_of_birth}}</P></td>
									</tr>

									<!-- marital status -->
									<tr>
										<td class="col-md-3"></td>
										<td class="col-md-3"><p>Marital status:</p></td>
										<td class="col-md-6"><P>{{user.userdetail.get_marital_display}}</P></td>
									</tr>
								</table>
							</div>
						</div>
						<!-- contact detail -->
						<div class="page-header"></div>						
						<div class="row">
							<div class="col-md-12">
								<table class="table borderless">
									<!-- email -->
									<tr>
										<th class="col-md-3"><p>Contact Details</p></th>
										<td class="col-md-3"><p>Email :</p></td>
										<td class="col-md-6">{{user.email}}</td>
									</tr>

									<!-- phone -->
									<tr>
										<td class="col-md-3"></td>
										<td class="col-md-3"><p>Phone :</p></td>
										<td class="col-md-6">{{user.userdetail.phone}}</td>
									</tr>
								</table>
							</div>
						</div>
						<!-- address -->
						<div class="page-header"></div>
						<div class="row">
							<div class="col-md-12">
								<table class="table borderless">
									<!-- address line -->
									<tr>
										<th class="col-md-3"><p>Address</p></th>
										<td class="col-md-3"><p>Address line:</p></td>
										<td class="col-md-6"><p>{{user.userdetail.address}}</p></td>
									</tr>

									<!-- street -->
									<tr>
										<td class="col-md-3"></td>
										<td class="col-md-3"><p>Street :</p></td>
										<td class="col-md-6"><p>{{user.userdetail.street}}</p></td>
									</tr>

									<!-- city -->
									<tr>
										<td class="col-md-3"></td>
										<td class="col-md-3"><p>City :</p></td>
										<td class="col-md-6"><p>{{user.userdetail.city}}</p></td>
									</tr>

									<!-- state -->
									<tr>
										<td class="col-md-3"></td>
										<td class="col-md-3"><p>State :</p></td>
										<td class="col-md-6"><p>{{user.userdetail.state}}</p></td>
									</tr>

									<!-- zip coe -->
									<tr>
										<td class="col-md-3"></td>
										<td class="col-md-3"><p>Zip code :</p></td>
										<td class="col-md-6"><p>{{user.userdetail.zip_code}}</p></td>
									</tr>
								</table>
							</div>
							
	
						</div>
						<!-- extra note -->
						<div class="page-header"></div>
						<div class="row">
							<!-- displaying the extra note -->
							<div class="col-md-12">
								<table class="table borderless">
									<!-- extra note -->
									<tr>
										<th class="col-md-3"><p>Extra Note</p></th>
										<td class="col-md-9"><p>{{user.userdetail.extra_note}}</p></td>
									</tr>
								</table>
							</div>
						</div>
						<!-- preffered communication -->
						<div class="page-header"></div>
						<div class="row">
							<div class="col-md-12">
								<!-- displaying all the prefered communications for the user in unordered list -->
								<table class="table borderless">
									<tr>
										<th class="col-md-3"><p>Preferred communication</p></th>
										<td class="col-md-3"></td>
										<td class="col-md-6"></td>
									</tr>

									<!-- mail -->
									<tr>
										<th class="col-md-3"></th>
										<td class="col-md-3"><p>Mail :</p></td>
										<td class="col-md-6">{% if user.userdetail.mail %}<span class="glyphicon glyphicon-ok"></span>{% endif%}</td>
									</tr>

									<!-- message -->
									<tr>
										<td class="col-md-3"><p></p></td>
										<td class="col-md-3"><p>Message :</p></td>
										<td class="col-md-6"><P>{% if user.userdetail.message %}<span class="glyphicon glyphicon-ok"></span>{% endif%}</P></td>
									</tr>

									<!-- phone call -->
									<tr>
										<td class="col-md-3"><p></p></td>
										<td class="col-md-3"><p>Phone call:</p></td>
										<td class="col-md-6"><P>{% if user.userdetail.phonecall %}<span class="glyphicon glyphicon-ok"></span>{% endif%}</P></td>
									</tr>

									<!-- other -->
									<tr>
										<td class="col-md-3"><p></p></td>
										<td class="col-md-3"><p>Other:</p></td>
										<td class="col-md-6"><P>{% if user.userdetail.other %}<span class="glyphicon glyphicon-ok"></span>{% endif%}</P></td>
									</tr>
								</table>
																
							</div>
						</div>							
		            </div> 
				</div>
			</div> <!--row profile-->
		</div>	
		
		<!-- footer -->
		{% include 'footer.html'%}

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

		<!-- Scrolling Nav JavaScript -->
	    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
	    <script src="{% static 'js/scrolling-nav.js' %}"></script>
	</body>
</html>